### ISSUE TITLE
Incompatibility with HPA on Deployments

### ISSUE THREAD

**Issue by ollymaunder-dnv** [dnv-gssit/kubeit-charts#12]
There is a problem with the app-of-apps chart when it's used with applications that use HPA for scaling. This also affects apps which use KEDA - because KEDA implements scaling via HPA.

When HPA scales up the number of pods, it changes the `replica` value on the Deployment. ArgoCD sees this as a difference to the desired manifest, and so it syncs and changes the number of replicas back to the value specified in the chart, or 1 by default. This causes any new pods to be terminated.

Then HPA tries to scale up the number of pods again, and then ArgoCD syncs and kills them all again. This results in a constant fight between ArgoCD and HPA.

A solution is to tell ArgoCD to ignore the `replica` value when deciding whether an Application is out of sync. [There is an example in the ArgoCD docs](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs):

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:

  ignoreDifferences:
  - group: "apps"
    kind: "Deployment"
    jsonPointers:
    - /spec/replicas

  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
```
